import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import Amplify from 'aws-amplify'
import { Authenticator, AmplifyProvider, Theme } from '@aws-amplify/ui-react'
import '@aws-amplify/ui-react/styles.css'
import useEnv from '../lib/useEnv'

function MyApp({ Component, pageProps }: AppProps) {
  const { env } = useEnv()

  if (!env) return <>Loading...</>

  Amplify.configure({
    Auth: {
      userPoolId: env.cognitoUserPoolId,
      userPoolWebClientId: env.cognitoUserPoolWebClientId
    }
  })

  const themeBlue: Theme = {
    name: 'blue',
    tokens: {
      colors: {
        brand: {
          primary: {
            10: { value: 'rgba(25,120,200,0.1)' },
            20: { value: 'rgba(25,120,200,0.2)' },
            40: { value: 'rgba(25,120,200,0.4)' },
            60: { value: 'rgba(25,120,200,0.6)' },
            80: { value: 'rgb(25,120,200)' },
            90: { value: 'rgb(25,120,200)' },
            100: { value: 'rgb(25,120,200)' }
          }
        }
      }
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AmplifyProvider theme={themeBlue}>
        <Authenticator.Provider>
          <Component {...pageProps} />
        </Authenticator.Provider>
      </AmplifyProvider>
    </>
  )
}

export default MyApp
